<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

  /**
   * @return Query
   */
  public function queryLatest()
  {
      return $this->getEntityManager()
          ->createQuery('
              SELECT a
              FROM AppBundle:Article a
              WHERE a.enabled = true
              ORDER BY a.updatedAt, a.createdAt DESC
          ')
      ;
  }

  /**
   * @param int $page
   *
   * @return
   */
  public function findLatest($page = 1)
  {
      $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryLatest(), false));
      $paginator->setMaxPerPage(Article::NUM_ITEMS);
      $paginator->setCurrentPage($page);

      return $paginator;
  }
}
