<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use AppBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

  /**
   *
   * @return
   */
  public function findActiveCategory()
  {
      return $this->getEntityManager()
          ->createQuery('
              SELECT c
              FROM AppBundle:Category c
              LEFT OUTER JOIN AppBundle:Product p WITH p.category = c.id
              LEFT OUTER JOIN AppBundle:Subcategory s WITH p.subcategory = s.id
              WHERE c.enabled = true
              ORDER BY c.name ASC
          ')->getResult();
      
//       $resultsObjects = null;
//       foreach ($results as $result) {
//           $resultsObjects[] = new Category($result);
//       }
//       return $resultsObjects;
      
  }
}
