<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

  /**
   * Recuperate last enabled product
   * @param cid : Category id  
   * @return Query
   */
  public function queryLatest($params)
  {
      $queryString = '
              SELECT p
              FROM AppBundle:Product p
              INNER JOIN AppBundle:Category c WITH p.category = c.id
              LEFT OUTER JOIN AppBundle:Subcategory s WITH p.subcategory = s.id
              WHERE p.enabled = true
            ';
      
      $queryOrder = '
            ORDER BY p.name ASC, c.name ASC
            ';
      
      if(isset($params))
      {
        
        $queryFilter = $this->getFilters($params);
        $query = $this->getEntityManager()->createQuery($queryString .  $queryFilter . $queryOrder);
        $this->addParameters($params, $query);
        return $query;    
      } else {
        return $this->getEntityManager()->createQuery($queryString . $queryOrder);
      }
  }

  /**
   * @param int $page
   *
   * @return
   */
  public function findLatest($page, $params)
  {
      $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryLatest($params), false));
      $paginator->setMaxPerPage(Product::NUM_ITEMS);
      $paginator->setCurrentPage($page);

      return $paginator;
  }
  
  /**
   * Add filter for request
   * @param array $params
   * @param unknown $query
   */
  private function addParameters($params, &$query) {
      if(isset($params['category'])) {
          $query->setParameter('cid', $params['category']);
      }
      if (isset($params['subcategory'])) {
          $query->setParameter('sid', $params['subcategory']);
      }
  }
  
  private function getFilters($params) {
      $queryFilter = '';
      
      if(isset($params['category'])) {
          $queryFilter .= ' AND c.id = :cid ';
      }
      if (isset($params['subcategory'])) {
          $queryFilter .= ' AND s.id = :sid ';
      }
      
      return $queryFilter;
  }
}
