<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends EntityRepository
{

  /**
   * @return Query
   */
  public function test($uid)
  {
    $query = $this->getEntityManager()
      ->createQuery('
              SELECT p
              FROM AppBundle:Purchase p
              INNER JOIN AppBundle:User u
              WITH p.buyer = u.id
              WHERE p.buyer = :uid
              ORDER BY p.deliveryDate DESC
          ')
      ;
      $query->setParameter('uid', $uid);
      return $query->getResult();;
  }

}
