easy_admin:
    entities:
        Category:
            label: menu.categories
            class: AppBundle\Entity\Category
            list:
                title: categories.list
                fields: ['id', 'enabled', 'name']
            new:
                title: category.new
            edit:
                title: category.edit
