easy_admin:
    entities:
        Category:
            label: menu.categories
            class: AppBundle\Entity\Category
            list:
                title: categories.list
                fields: ['id', 'enabled', 'name']
                sort: ['name', 'ASC']
                actions: ['show', 'edit', 'delete']
            new:
                title: category.new
                fields:
                    - 'enabled'
                    - 'name'
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: false } }
                    - 'subcategories'
                    - 'products'
            edit:
                title: category.edit
                fields:
                    - 'enabled'
                    - 'name'
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: false } }
                    - 'subcategories'
                    - 'products'
