easy_admin:
    entities:
        Enterprise:
            disabled_actions: ['delete', 'new']
            label: menu.enterprise
            class: AppBundle\Entity\Enterprise
            list:
                title: article.list
                fields:
                  - 'id'
                  - 'enabled'
                  - 'title'
                  - 'updatedAt'
                  - 'createdAt'
            new:
                title: article.new
                fields:
                    - 'enabled'
                    - 'title'
                    - { property: 'contains', type: 'ckeditor' }
            edit:
                title: article.edit
                fields:
                    - 'enabled'
                    - 'title'
                    - { property: 'contains', type: 'ckeditor' }
