easy_admin:
    entities:
        GeographicCoordinates:
            label: menu.geographic_coordinates
            class: AppBundle\Entity\GeographicCoordinates
            list:
                title: geographic_coordinates.list
                fields:
                  - 'id'
                  - 'name'
                  - 'latitude'
                  - 'longitude'
            new:
                title: geographic_coordinates.new
                fields:
                    - 'name'
                    - 'latitude'
                    - 'longitude'
            edit:
                title: geographic_coordinates.edit
                fields:
                    - 'name'
                    - 'latitude'
                    - 'longitude'
