easy_admin:
    entities:
        Measurement:
            label: menu.measurements
            class: AppBundle\Entity\Measurement
            list:
                title: measurement.list
                fields: ['id', 'enabled', 'name', 'shortname']
            new:
                title: measurement.new
            edit:
                title: measurement.edit
