easy_admin:
    entities:
        Product:
            label: menu.products
            class: AppBundle\Entity\Product
            list:
                title: product.list
                fields:
                  - 'id'
                  - 'enabled'
                  - 'name'
                  - 'quantity'
                  - 'description'
                  #- { property: 'photo', type: 'image', base_path: %app.path.product_photos% }
                  - { property: 'image', type: 'image', base_path: %app.path.product_images% }
                  - { property: 'createdAt', format: 'j/m/Y' }
                  - 'price'
                  - 'category'
                  - 'measurement'
            new:
                title: product.new
                fields:
                    - 'enabled'
                    - 'name'
                    - 'quantity'
                    - 'price'
                    - 'taxRate'
                    #- { property: 'photoFile', type: 'file' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - 'category'
                    - 'measurement'
                    - 'weight'
                    - { property: 'description', type: 'ckeditor' }
            edit:
                title: product.edit
                fields:
                    - 'enabled'
                    - 'name'
                    - 'quantity'
                    - 'price'
                    - 'taxRate'
                    #- { property: 'photoFile', type: 'Vich\UploaderBundle\Form\Type\VichImageType', type_options: { required: true } }
                    - { property: 'imageFile', type: 'vich_image' }
                    - 'category'
                    - 'measurement'
                    - 'weight'
                    - { property: 'description', type: 'ckeditor' }
